sudo: required

language: go

go:
  - "1.11"

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - K8S_VERSION="v1.10.0"
    - MINIKUBE_VERSION="v0.28.2"

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.MD)|(\.png)|(\.pdf)|^(doc/)|^(MAINTAINERS)|^(LICENSE)'; then
        echo "Only doc files were updated, not running the CI."
        exit
      fi
#  - docker run -d -p 2399:2399 quay.io/coreos/etcd:v3.3.10 /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2399 -listen-client-urls http://0.0.0.0:2399

# Skip downloading deps.
install: true

matrix:
  include:
    - go: "1.11"
      sudo: required
      env:
        - "TEST_SUITE=csi"
        - "TEST_CLUSTER=openshift"
      name: CSI setup on OpenShift
    - go: "1.11"
      sudo: required
      env:
        - "TEST_SUITE=csi"
        - "TEST_CLUSTER=minikube"
      name: CSI setup on Minikube
    - go: "1.11"
      sudo: required
      env:
        - "TEST_SUITE=intree"
        - "TEST_CLUSTER=openshift"
      name: In-tree plugin setup on OpenShift
    - go: "1.11"
      sudo: required
      env:
        - "TEST_SUITE=intree"
        - "TEST_CLUSTER=minikube"
      name: In-tree plugin setup on Minikube


script:
  - ./test/e2e.sh $TEST_CLUSTER $TEST_SUITE
