
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.8"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.8"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.8"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.8"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "v0.0.6"

[[constraint]]
  name = "github.com/storageos/go-api"
  branch = "master"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.1"

[[constraint]]
  name = "github.com/darkowlzz/daemonset-job"
  branch = "master"
