apiVersion: "node.storageos.com/v1alpha1"
kind: "StorageOS"
metadata:
  name: "example-storageos"
  namespace: "default"
spec:
  # join:
  enableCSI: true
  secretRefName: "storageos-api"
  secretRefNamespace: "default"
  namespace: "storageos"
  service:
    name: "storageos"
    type: "ClusterIP"
    externalPort: 5705
    internalPort: 5705
  # sharedDir should be set if running kubelet in a container.  This should
  # be the path shared into to kubelet container, typically:
  # "/var/lib/kubelet/plugins/kubernetes.io~storageos".  If not set, defaults
  # will be used.
  # sharedDir:

---
apiVersion: v1
kind: Secret
metadata:
  name: "storageos-api"
  namespace: "default"
  labels:
    app: "storageos"
type: "kubernetes.io/storageos"
data:
  # echo -n '<secret>' | base64
  apiAddress: c3RvcmFnZW9zOjU3MDU=
  apiUsername: c3RvcmFnZW9z
  apiPassword: c3RvcmFnZW9z
