apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storageoses.node.storageos.com
spec:
  group: node.storageos.com
  names:
    kind: StorageOS
    listKind: StorageOSList
    plural: storageoses
    singular: storageos
  scope: Namespaced
  version: v1alpha1
