kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: storageoscluster-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: storageoscluster-operator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageoscluster-operator-sa
  namespace: default
  labels:
    app: storageos
